### PR TITLE
Add cubic-bezier to the NameFormat css whitelist

### LINKED ISSUE #894: Gives warning on cubic-bezier in snake case setting
Gives warning on cubic-bezier in snake case setting
even tho correct syntax is used.

untitledss

### PR DESCRIPTION
**Pull request by srawlins**
Fixes #894

### CODE REVIEW

**Comment by sds** [comment]
Thanks @srawlins!

**Comment by dzhytomyrsky** [comment]
Is cubic-bezier in scss whitelist?

**Comment by srawlins** [comment]
@dzhytomyrsky What is an scss whitelist?

**Comment by sds** [comment]
If you're referring to whether this PR has been released, as of a few minutes ago the answer is yes!

[0.54.0](https://github.com/brigade/scss-lint/releases/tag/v0.54.0) includes the `cubic-bezier` addition to the whitelist.

**Pull request merged**
