### PR TITLE
Configure to not lint DuplicateProperty on consecutive lines

### LINKED ISSUE #715: DuplicateProperty consecutive duplicates
In #114, after it was closed, a discussion began regarding how CSSLint [ignores consecutive duplicates](https://github.com/CSSLint/csslint/wiki/Disallow-duplicate-properties). The idea is that if you write:

```css
a {
  background: #fff;
  background: rba(255, 255, 255, .5);
}
```

then you probably did so intentionally, since its visually so easy to see that the same property is defined twice. If you hadn't meant this to happen, you would have seen it and fixed it.

I'd be happy to contribute a config for DuplicateProperty, like `ignore_consecutive` or `allow_consecutive`, or something.

### PR DESCRIPTION
**Pull request by srawlins**
Fixes #715. CC #114.

Explanation added to README.

### CODE REVIEW

**Comment by lencioni** [comment]
Do you think it would be a good idea to make the ignore option be a whitelist instead of a boolean? Or at least use a whitelist internally? I ask because if you are one to sort your properties, you might end up with consecutive duplicates when you don't actually want them but won't be warned. Restricting this to a whitelist seems like a good way to go, to minimize this problem.

**Comment by srawlins** [comment]
I'd be happy to change it to that. Or maybe we could have both features.

I like the consecutive lines solution because I think it has _less_ chance of accidentally allowing a duplicate than the whitelist solution. The whitelist solution can definitely accidentally allow a duplicate of `background` where the duplicate is unintentional.

The consecutive solution, however, only allows duplicates by accident if the humans also missed a duplicate consecutive property.

**Comment by lencioni** [comment]
Oh, I meant using a whitelist in addition to the consecutive check.

**Comment by srawlins** [comment]
Oh I see. So you would specify something like:

```
  ignore_consecutive:
    - background
    - transition
```

I like this idea.

**Comment by lencioni** [comment]
Yeah, something like that. I think perhaps it should come with a default list of properties built in that commonly are used with fallbacks, so it might need to use two options--one to turn on/off this behavior and another to customize the list.

**Comment by lencioni** [comment]
However, if you are using something like `calc` and want fallbacks for that, you might need to include a lot of properties in your whitelist. Perhaps the whitelist should look at values instead of properties? But that gets hard if you are using a Sass function...

**Comment by srawlins** [comment]
Awesome, pushed and squashed. I didn't look into the *values* whitelist. Too complicated :grinning:

**Comment by lencioni** [comment]
Besides the comment about the code block, this looks good to me. Want to fix that and add a changelog entry?

**Comment by srawlins** [comment]
Thanks! Done

**Pull request closed without merging**
