### PR TITLE
Fix modifier portion of BEM

### PR DESCRIPTION
**Pull request by conatus**
The current implementation does not understand the "modifier" portion of the BEM syntax.

I copied out the BEM regex as in the code to test it http://regexr.com/3apmp

As you can see adding a simple modifier in the standard BEM way doesn't work.

The implementation I have done here fixes it as the follow regex shows http://regexr.com/3apms

Thanks very much.

### CODE REVIEW

**Comment by sds** [comment]
Hey @conatus,

I might be mistaken, but I believe the `hyphenated_BEM` syntax is what you are looking for? Please see the discussion in #335.

**Comment by conatus** [comment]
Thanks for this - at least I made a PR to fix this "problem" amongst the other tickets!

Perhaps you could make this clearer in the documentation or alternatively rename BEM to "classic/strict/orthodox BEM" or something? Every tutorial I have seen, including some very recent ones uses the format that diverts slightly from the original formulation. The fact I wasn't the first to have this problem illustrates something is afoot.

**Comment by sds** [comment]
That's a fair point, @conatus. You're definitely not the first to be tripped up by this and certainly won't be the last unless we do something.

I like your suggestion of renaming the convetion. I've chosen `strict_BEM` and made the change in 4d253c8337d8a99a69e87dbc1d90b23a1f15e089. Thanks!

**Comment by conatus** [comment]
Thanks very much, this is cool.

**Pull request closed without merging**
