### PR TITLE
Lint string aswell as files

### PR DESCRIPTION
**Pull request by teoljungberg**
References #435

### CODE REVIEW

**Comment by teoljungberg** [comment]
I'm unsure how a test-case for this should look, any ideas @sds ?

**Comment by sds** [comment]
Hey @teoljungberg, thanks for the pull request.

The reason I don't want to revert back to the previous behavior of testing for file existence to determine whether to treat a string as code or a file is because it's not terribly clean.

For example, while perhaps a silly example, the string `p{}` is a valid file name as well as valid SCSS code. Do we prioritize loading the file over parsing it as code in this case? (again, we can argue about whether this is practical, but it is an issue).

I was hoping we could adjust the runner to instead accept an options hash with `files` or `source` keys, and then lint based on whichever keys are present. This changes the signature, but I think is a cleaner approach if we want to support this in a proper way.

**Comment by teoljungberg** [comment]
> I was hoping we could adjust the runner to instead accept an options hash with files or source keys, and then lint based on whichever keys are present. This changes the signature, but I think is a cleaner approach if we want to support this in a proper way.

@sds - That's sounds like a good approach. I wanted to make the smallest imprint at first to get this kind of feedback. I'll update the PR with the comments you made

**Comment by tobiashm** [comment]
Maybe if the input was just a stream, which might come from a file, but could also come from `stdin` or in the form of `StringIO`.

I would really like the CLI to be able to accept a `stdin` stream, as that would make integration with other tools, like editors, much easier.

**Comment by sds** [comment]
Closing this pull request as it seems to have been abandoned. Feel free to open a new one with the [comments above](https://github.com/brigade/scss-lint/pull/491#issuecomment-112192160) addressed. Thanks!

**Pull request closed without merging**
