### PR TITLE
Add --color and --no-color options

### PR DESCRIPTION
**Pull request by lencioni**
We want to allow people to force the use or non-use of color when
running scss-lint. This commit does this by extracting the logging into
a Logger class and adding `--color` and `--no-color` options.

For this code, I essentially brought over the same stuff that was done
in HamlLint.

Addresses #364

### CODE REVIEW

**Comment by lencioni** [comment]
Ack, it looks like this might not entirely do the job, since default reporter still adds color via the rainbow gem. Since the reporters in this project return strings instead of printing them, and since Logger prints things, how do you think we should tackle this @sds?

**Comment by lencioni** [comment]
I think I'm just going to add a logger argument to the `Reporter` initialize and expose some methods for coloring text on the logger.

**Comment by sds** [comment]
Thanks for the pull request, @lencioni.

Yes, we'll need to rewrite the reporters to use the `Logger` class, as all output should be delegated to it.

**Comment by lencioni** [comment]
Alright, I just pushed a new version. Let me know what you think!

**Comment by sds** [comment]
Thanks so much for implementing this, @lencioni!

**Comment by lencioni** [comment]
\o/

**Pull request merged**
