### PR TITLE
Add box-sizing to smacss

### PR DESCRIPTION
**Pull request by danieldiekmeier**

### CODE REVIEW

**Comment by danieldiekmeier** [comment]
I hope this is the right place for it. I also thought about putting it near the top, between `display` and `position`?

**Comment by sds** [comment]
Since we at @brigade don't subscribe to the SMACSS philosophy per se, I can't speak to whether this would be an appropriate place to order `box-sizing`.

Now that an implementation for #440 has landed on `master`, I'm hoping someone from the community can step forward and "own" any SMACSS related configuration, so we can remove this default ordering from `scss-lint` (and developers who want it can load the plugin separately).

Until #440 gets released, can anyone else who uses SMACSS vouch for this ordering?

**Comment by danieldiekmeier** [comment]
Would it also be possible to add support for something like `order: 'my-ordering.txt'`, so I don't need to have the whole CSS definition inside my yml?

**Comment by danieldiekmeier** [comment]
I take that back.

**Pull request closed without merging**
